name: Generate Track Sitemap
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Sitemap
        run: |
          node -e "
          const fs = require('fs');
          const totalTracks = 376;
          let xml = '<?xml version=\"1.0\" encoding=\"UTF-8\"?>\\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\\n';
          
          // Add static pages
          xml += '  <url>\\n    <loc>https://www.frithhilton.com.ng/</loc>\\n  </url>\\n';
          xml += '  <url>\\n    <loc>https://www.frithhilton.com.ng/pages/bio.html</loc>\\n  </url>\\n';
          
          // Generate track URLs 1-376
          for (let id = 1; id <= totalTracks; id++) {
            xml += \`  <url>\\n    <loc>https://www.frithhilton.com.ng/pages/freshPlayer.html?track=\${id}</loc>\\n  </url>\\n\`;
          }
          
          xml += '</urlset>';
          
          fs.writeFileSync('sitemap.xml', xml);
          console.log('✅ Sitemap generated with 376 track URLs!');
          console.log('Total URLs: 378 (376 tracks + 2 static pages)');
          console.log('File size: ', Buffer.byteLength(xml, 'utf8'), 'bytes');
          "

      - name: Commit Sitemap Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sitemap.xml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update sitemap.xml with 376 track URLs (1-376)"
            git push
            echo "✅ Sitemap committed and pushed successfully!"
          fi

      - name: Validate Sitemap
        run: |
          if [ -f sitemap.xml ]; then
            echo "✅ Sitemap generated successfully!"
            echo "File size: $(wc -c < sitemap.xml) bytes"
            echo "Line count: $(wc -l < sitemap.xml) lines"
            echo "Track URLs: $(grep -c 'track=' sitemap.xml)"
            echo "Sample URLs:"
            head -n 20 sitemap.xml | tail -n 10
            echo ""
            echo "Submit this sitemap in GSC: https://www.frithhilton.com.ng/sitemap.xml"
          else
            echo "❌ Sitemap generation failed"
            exit 1
          fi